// <auto-generated />
using System;
using BeautyControl.API.Infra.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace BeautyControl.API.Infra.Data.Migrations
{
    [DbContext(typeof(AppDataContext))]
    partial class AppDataContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasDefaultSchema("Business")
                .HasAnnotation("ProductVersion", "7.0.5")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("BeautyControl.API.Domain.Employees.Employee", b =>
                {
                    b.Property<int>("Id")
                        .HasColumnType("int");

                    b.Property<bool>("Active")
                        .HasColumnType("bit");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("VARCHAR(256)");

                    b.Property<int>("Position")
                        .HasColumnType("INT");

                    b.HasKey("Id");

                    b.ToTable("Employees", "Business");
                });

            modelBuilder.Entity("BeautyControl.API.Domain.Products.Product", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<short>("Category")
                        .HasColumnType("SMALLINT");

                    b.Property<DateTime>("CreationDate")
                        .HasColumnType("DATETIME");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("VARCHAR(2048)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("VARCHAR(128)");

                    b.Property<int>("Quantity")
                        .HasColumnType("INT");

                    b.Property<int>("RunningOutOfStock")
                        .HasColumnType("INT");

                    b.Property<byte>("Status")
                        .HasColumnType("TINYINT")
                        .HasColumnName("StatusStock");

                    b.HasKey("Id");

                    b.ToTable("Products", "Business");
                });

            modelBuilder.Entity("BeautyControl.API.Domain.Employees.Employee", b =>
                {
                    b.OwnsOne("BeautyControl.API.Domain.Employees.Email", "Email", b1 =>
                        {
                            b1.Property<int>("EmployeeId")
                                .HasColumnType("int");

                            b1.Property<string>("Address")
                                .IsRequired()
                                .HasColumnType("VARCHAR(256)")
                                .HasColumnName("Email");

                            b1.HasKey("EmployeeId");

                            b1.ToTable("Employees", "Business");

                            b1.WithOwner()
                                .HasForeignKey("EmployeeId");
                        });

                    b.Navigation("Email");
                });

            modelBuilder.Entity("BeautyControl.API.Domain.Products.Product", b =>
                {
                    b.OwnsOne("BeautyControl.API.Domain.Products.Image", "Image", b1 =>
                        {
                            b1.Property<int>("ProductId")
                                .HasColumnType("int");

                            b1.Property<string>("Name")
                                .HasColumnType("VARCHAR(256)")
                                .HasColumnName("ImageName");

                            b1.Property<string>("Url")
                                .HasColumnType("VARCHAR(2048)")
                                .HasColumnName("ImageUrl");

                            b1.HasKey("ProductId");

                            b1.ToTable("Products", "Business");

                            b1.WithOwner()
                                .HasForeignKey("ProductId");
                        });

                    b.Navigation("Image");
                });
#pragma warning restore 612, 618
        }
    }
}
